"""add region isin figi to assets

Revision ID: 7e58b8144479
Revises: c9bcdf39c2c9
Create Date: 2026-03-15 16:39:37.048775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e58b8144479'
down_revision: Union[str, Sequence[str], None] = 'c9bcdf39c2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('region', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('region_override', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('isin', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('figi', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'figi')
    op.drop_column('assets', 'isin')
    op.drop_column('assets', 'region_override')
    op.drop_column('assets', 'region')
    # ### end Alembic commands ###
