"""restructure returns to frequency model

Revision ID: c9bcdf39c2c9
Revises: e865a7730848
Create Date: 2026-03-13 18:52:22.938705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bcdf39c2c9'
down_revision: Union[str, Sequence[str], None] = 'e865a7730848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('frequency', sa.String(), nullable=False))
    op.add_column('returns', sa.Column('value', sa.Float(), nullable=False))
    op.drop_constraint(op.f('uq_return_ticker_date'), 'returns', type_='unique')
    op.create_unique_constraint('uq_return_ticker_date_freq', 'returns', ['ticker', 'date', 'frequency'])
    op.drop_column('returns', 'monthly_return')
    op.drop_column('returns', 'daily_return')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('daily_return', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('returns', sa.Column('monthly_return', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint('uq_return_ticker_date_freq', 'returns', type_='unique')
    op.create_unique_constraint(op.f('uq_return_ticker_date'), 'returns', ['ticker', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_column('returns', 'value')
    op.drop_column('returns', 'frequency')
    # ### end Alembic commands ###
