"""fix region column length

Revision ID: ff1ae7e38be3
Revises: e507b41117f8
Create Date: 2026-03-13 17:34:42.446210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1ae7e38be3'
down_revision: Union[str, Sequence[str], None] = 'e507b41117f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('factor_returns', 'region',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('factor_returns', 'region',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###
